baseURL = "https://efragments.com"
languageCode = "en-gb"
title = "efragments"

[params]
author = "Will Hughes"
authorimage = "/img/headshot.png"
dateformat = "1 January 2000"

[params.font]
name = "Merriweather"
weights = "300,400"

[[params.elsewhere]]
name = "Photographs"
url = "https://arjibarji.wordpress.com/"

[[params.elsewhere]]
name = "Academic work"
url = "https://www.reading.ac.uk/cme/staff/professor-will-hughes"

[[params.elsewhere]]
name = "CM Abstracts"
url = "https://cmabstracts.com"

[params.unpkg]
css = ["normalize.css/normalize.css"]
